# Generated by Django 3.1.7 on 2021-03-19 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('pro_no', models.AutoField(primary_key=True, serialize=False)),
                ('pro_client_id', models.CharField(max_length=60)),
                ('pro_client_nm', models.CharField(max_length=60)),
                ('pro_active_yn', models.CharField(max_length=1)),
                ('pro_url', models.CharField(max_length=250)),
                ('pro_craw_url', models.CharField(max_length=250)),
                ('pro_create_dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
