# Generated by Django 3.1.7 on 2021-03-24 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwmonitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='pro_active_yn',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=1),
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('server_no', models.AutoField(primary_key=True, serialize=False)),
                ('server_os', models.CharField(max_length=120)),
                ('server_was', models.CharField(max_length=120)),
                ('server_was_path', models.CharField(max_length=250)),
                ('server_start_time', models.CharField(max_length=120)),
                ('server_java_version', models.CharField(max_length=60)),
                ('server_hdd_total', models.IntegerField(default=0)),
                ('server_memory_total', models.IntegerField(default=0)),
                ('server_db_type', models.CharField(max_length=120)),
                ('server_db_url', models.CharField(max_length=250)),
                ('pro_no', models.ForeignKey(db_column='pro_no', on_delete=django.db.models.deletion.CASCADE, related_name='ProjectInfo', to='jwmonitor.projectinfo')),
            ],
        ),
    ]
