# Generated by Django 3.1.7 on 2021-03-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwmonitor', '0002_auto_20210324_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverinfo',
            old_name='server_db_url',
            new_name='server_java_home',
        ),
    ]
