# Generated by Django 3.1.7 on 2021-03-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwmonitor', '0003_auto_20210324_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='pro_craw_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='pro_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='server_db_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='server_java_home',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='server_java_version',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='server_os',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='server_start_time',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='server_was',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='server_was_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
