# Generated by Django 3.1.7 on 2021-03-24 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jwmonitor', '0004_auto_20210324_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='server_create_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='pro_active_yn',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='Y', max_length=1),
        ),
    ]
