# Generated by Django 3.1.7 on 2021-03-24 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwmonitor', '0005_auto_20210324_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='pro_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwmonitor.projectinfo'),
        ),
    ]
