# Generated by Django 3.1.7 on 2021-04-05 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwmonitor', '0006_auto_20210324_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverinfo',
            name='pro_no',
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='server_pro_no',
            field=models.ForeignKey(db_column='server_pro_no', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_pro_no', to='jwmonitor.projectinfo'),
        ),
    ]
