# Generated by Django 3.1.7 on 2021-04-05 07:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jwmonitor', '0007_auto_20210405_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpuInfo',
            fields=[
                ('cpu_no', models.AutoField(primary_key=True, serialize=False)),
                ('cpu_usage', models.IntegerField(default=0)),
                ('cpu_idle', models.IntegerField(default=0)),
                ('cpu_create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_server_no', models.ForeignKey(db_column='cpu_server_no', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpu_server_no', to='jwmonitor.serverinfo')),
            ],
        ),
    ]
