# Generated by Django 3.1.7 on 2021-04-06 04:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jwmonitor', '0008_cpuinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryInfo',
            fields=[
                ('memory_no', models.AutoField(primary_key=True, serialize=False)),
                ('memory_usage', models.IntegerField(default=0)),
                ('memory_idle', models.IntegerField(default=0)),
                ('memory_create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('memory_server_no', models.ForeignKey(db_column='memory_server_no', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_server_no', to='jwmonitor.serverinfo')),
            ],
        ),
        migrations.CreateModel(
            name='HddInfo',
            fields=[
                ('hdd_no', models.AutoField(primary_key=True, serialize=False)),
                ('hdd_usage', models.IntegerField(default=0)),
                ('hdd_idle', models.IntegerField(default=0)),
                ('hdd_create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('hdd_server_no', models.ForeignKey(db_column='hdd_server_no', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hdd_server_no', to='jwmonitor.serverinfo')),
            ],
        ),
    ]
