# Generated by Django 3.1.7 on 2021-04-07 02:49

from django.db import migrations, models
import django.utils.timezone
import jwmonitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('jwmonitor', '0009_hddinfo_memoryinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_data', models.JSONField(default=jwmonitor.models.config_default)),
                ('con_update_dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='pro_active_yn',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=1),
        ),
    ]
