# Generated by Django 3.1.7 on 2021-04-08 02:27

from django.db import migrations, models
import jwmonitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('jwmonitor', '0010_auto_20210407_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='id',
        ),
        migrations.AddField(
            model_name='config',
            name='con_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='con_id',
            field=models.CharField(default=jwmonitor.models.random_string, max_length=120),
        ),
        migrations.AddField(
            model_name='config',
            name='con_no',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='con_data',
            field=models.CharField(default='', max_length=255),
        ),
    ]
