# Generated by Django 3.1.7 on 2021-04-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwmonitor', '0011_auto_20210408_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='con_id',
            field=models.CharField(default='', max_length=120),
        ),
    ]
