# Generated by Django 3.1.7 on 2021-04-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwmonitor', '0012_auto_20210408_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='con_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='pro_active_yn',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='Y', max_length=1),
        ),
    ]
