# Generated by Django 3.1.7 on 2021-04-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwmonitor', '0013_auto_20210413_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='pro_domain',
            field=models.TextField(blank=True, null=True),
        ),
    ]
