# Generated by Django 3.1.7 on 2021-04-13 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jwmonitor', '0014_projectinfo_pro_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainLicense',
            fields=[
                ('dl_no', models.AutoField(primary_key=True, serialize=False)),
                ('dl_referer', models.CharField(max_length=255)),
                ('dl_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('dl_confirm', models.CharField(default='N', max_length=1)),
                ('dl_create_dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
