# Generated by Django 3.1.7 on 2021-04-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwmonitor', '0015_domainlicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainlicense',
            name='dl_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='pro_active_yn',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=1),
        ),
    ]
