# Generated by Django 3.1.7 on 2021-04-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwmonitor', '0016_auto_20210414_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainlicense',
            name='dl_host',
            field=models.CharField(default='NONE', max_length=255),
        ),
    ]
