# Generated by Django 3.1.7 on 2021-04-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwmonitor', '0017_domainlicense_dl_host'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DomainLicense',
            new_name='DomainInfo',
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='pro_active_yn',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='Y', max_length=1),
        ),
    ]
