# Generated by Django 3.1.7 on 2021-05-27 07:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jwmonitor', '0019_auto_20210428_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='pro_active_yn',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='Y', max_length=1),
        ),
        migrations.CreateModel(
            name='RealTimeInfo',
            fields=[
                ('re_no', models.AutoField(primary_key=True, serialize=False)),
                ('re_server_time', models.IntegerField(default=0)),
                ('re_server_status_code', models.CharField(max_length=12)),
                ('re_db_time', models.IntegerField(default=0)),
                ('re_db_status_code', models.CharField(max_length=12)),
                ('re_create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('re_pro_no', models.ForeignKey(db_column='re_pro_no', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_pro_no', to='jwmonitor.projectinfo')),
            ],
        ),
    ]
